stages:
  - build

Build for 7.0:
  stage: build
  variables:
    VERSION: "7.0"
  script:
    - apk add --no-cache bash
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg PHP_VERSION=$VERSION -t $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine -f ./.docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine
    - docker login -u $DOCKER_IO_LOGIN -p $DOCKER_IO_TOKEN
    - docker tag $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker push turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker logout

Build for 7.1:
  stage: build
  variables:
    VERSION: "7.1"
  script:
    - apk add --no-cache bash
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg PHP_VERSION=$VERSION -t $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine -f ./.docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine
    - docker login -u $DOCKER_IO_LOGIN -p $DOCKER_IO_TOKEN
    - docker tag $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker push turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker logout


Build for 7.2:
  stage: build
  variables:
    VERSION: "7.2"
  script:
    - apk add --no-cache bash
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg PHP_VERSION=$VERSION -t $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine -f ./.docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine
    - docker login -u $DOCKER_IO_LOGIN -p $DOCKER_IO_TOKEN
    - docker tag $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker push turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker logout


Build for 7.3:
  stage: build
  variables:
    VERSION: "7.3"
  script:
    - apk add --no-cache bash
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg PHP_VERSION=$VERSION -t $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine -f ./.docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine
    - docker login -u $DOCKER_IO_LOGIN -p $DOCKER_IO_TOKEN
    - docker tag $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker push turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker logout


Build for 7.4:
  stage: build
  variables:
    VERSION: "7.4"
  script:
    - apk add --no-cache bash
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg PHP_VERSION=$VERSION -t $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine -f ./.docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine
    - docker tag $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker login -u $DOCKER_IO_LOGIN -p $DOCKER_IO_TOKEN
    - docker tag $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker push turbosnail/php:$VERSION-fpm-nginx-alpine
    - docker tag $CI_REGISTRY_IMAGE:$VERSION-fpm-nginx-alpine turbosnail/php:latest
    - docker push turbosnail/php:latest
    - docker logout
