stages:
  - build

Build:
  stage: build
  script:
    - apk add --no-cache bash
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./build.sh $CI_REGISTRY_IMAGE
  except:
    - schedules